#!/bin/bash

docker build \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME \
    .

# squash it to make image much smaller
docker run --name tgagor-centos-stream $IMAGE_NAME true
docker export tgagor-centos-stream | docker import \
    --change 'CMD ["/bin/bash"]' \
    --change "LABEL org.opencontainers.image.schema-version=\"1.0\" org.opencontainers.image.title=\"CentOS Base Image\" org.opencontainers.image.vendor=\"CentOS\" org.opencontainers.image.licenses=\"GPL-2.0\" org.opencontainers.image.authors=\"https://github.com/tgagor\" org.opencontainers.image.source=\"https://github.com/tgagor/docker-centos-stream/\" org.opencontainers.image.url=\"https://github.com/tgagor/docker-centos-stream/blob/master/README.md\" org.opencontainers.image.created=\"$(date --rfc-3339=date)\"" \
    - $IMAGE_NAME
docker rm tgagor-centos-stream
